name: langchain
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.12.12=h716150d_1
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - blinker==1.9.0
      - build==1.3.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - chromadb==1.3.7
      - click==8.3.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - docstring-parser==0.17.0
      - durationpy==0.10
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.1
      - filetype==1.2.0
      - flatbuffers==25.12.19
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.9.0
      - google-api-core==2.28.0
      - google-auth==2.41.1
      - googleapis-common-protos==1.71.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipykernel==7.1.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.3
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - kubernetes==34.1.0
      - langchain==1.0.0
      - langchain-anthropic==1.0.0
      - langchain-chroma==1.1.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.2.4
      - langchain-google-genai==3.0.0
      - langchain-huggingface==1.2.0
      - langchain-mcp-adapters==0.1.11
      - langchain-openai==1.0.1
      - langchain-tavily==0.2.12
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-checkpoint-sqlite==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.38
      - lark==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mcp==1.19.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - narwhals==2.10.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.3.4
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai==2.6.1
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.4
      - ormsgpack==1.11.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pillow==12.0.0
      - platformdirs==4.5.0
      - posthog==5.4.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pypdf==6.5.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywin32==311
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - send2trash==1.8.3
      - sentence-transformers==5.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlite-vec==0.1.6
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.49.0
      - streamlit==1.51.0
      - streamlit-chat==0.1.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - typer==0.20.0
      - typer-slim==0.20.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uuid-utils==0.12.0
      - uvicorn==0.38.0
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\trimu\anaconda3\envs\langchain
